ModuleDescription=
ModuleLabel=ModelioAlchemist

command.Generate_from_Specifications_Document.label=Generate_from_Specifications_Document
command.Generate_from_Specifications_Document.tooltip=
command.G\u00E9n\u00E9rer_\u00E0_partir_d'un_cahier_de_charge.label=G\u00E9n\u00E9rer_\u00E0_partir_d'un_cahier_de_charge
command.G\u00E9n\u00E9rer_\u00E0_partir_d'un_cahier_de_charge.tooltip=
